### PR TITLE
Fixed bug where extension hangs due to server unavailability

### PR DESCRIPTION
**Pull request by willarmiros**
After following the [Jupyter Lab Extension](https://nbdefense.ai/getting-started/jupyter-lab-extension/) steps 1-3 (not including the activate step), when you press the "scan" button, the tool would hang in the loading state until you restart the server. This was because the connection to the NB Defense server cannot be established without activating the server extension, so when the request was sent it would never receive a response and therefore never change state away from loading.

To fix this, we catch the connection refused error that happens on rendering and use it to display an error message and disable the scan button until the server extension is activated. I changed the `DirtyStateWarning` component to be a generic warning/error message box so that it could be used to display the error message. See the attached screenshot for the error message. The "happy case" behavior is unchanged.

error-message

### CODE REVIEW

**Review by milesjos — CHANGES_REQUESTED** [review]
One small comment, but everything else looks great!

**Comment by willarmiros** [comment]
Seems the CI is now failing on the build step for some reason... will investigate

**Comment by milesjos** [comment]
It looks like IPython wasn't pinned and only supports Python >= 3.9
image

**Comment by willarmiros** [comment]
Investigation found that GH actions installs the latest version of IPython, v8.13.0, as a transitive dependency during the [jupyterlab installation step](https://github.com/protectai/nbdefense-jupyter/actions/runs/4833050182/jobs/8612961280#step:4:12). 8.13.0 is the first version to drop support for Python 3.8, and [it was released 9 hours ago](https://pypi.org/project/ipython/#history), hence why these tests passed yesterday but not today.

Per offline discussion w/ @milesjos, we found that SageMaker now uses Python 3.10 rather than 3.7 which was previously used, so we can safely upgrade the CI Python version to 3.9 to satisfy IPython while still supporting SageMaker.

**Review by milesjos — APPROVED** [review]
LGTM! We can drop support for Python 3.7 and 3.8 soon in a separate ticket

**Pull request merged**
